import type { Statement } from '@/lib/statements/interface'
import type { QueryState } from '@/lib/queries/enums'
import { EventPublisher } from '@/lib/events/publisher'
import type { QueryEventMap } from '@/lib/queries/events'

// there is a difference between the QueryResult.id and Query.id
//  QueryResult.id is generated by the database when a statement is successfully executed
//  Query.id is generated by the application when the query is created

export type QueryResult<T extends object = object> = {
  rows: Array<T>
  affectedRows: number | null
  duration: number
  id: string
}

export type PaginatedQueryResult<T extends object = object> = QueryResult<T> & {
  offset: number
  limit: number
}

export interface IQuery<T extends object = object>
  extends EventPublisher<QueryEventMap> {
  getId(): string
  getState(): QueryState
  getStatement(): Statement
  hasResult(): boolean
  getResult(): QueryResult<T> | PaginatedQueryResult<T> | null
  getError(): Error | null
  getTotalRowCount(): { min: number; isKnown: boolean }
  computeTotalRowCount(): Promise<void>
  // execute the query, if statement is a SELECT, the first 100 rows are stored in the result
  execute(): Promise<void>
  fetchRows(offset: number, limit: number): Promise<void>
  cancel(): void
}
