export const PostgresDataType = {
  BigInt: 'BIGINT',
  BigSerial: 'BIGSERIAL',
  Bit: 'BIT',
  BitVarying: 'BIT_VARYING',
  Boolean: 'BOOLEAN',
  Box: 'BOX',
  Bytea: 'BYTEA',
  Character: 'CHARACTER',
  CharacterVarying: 'CHARACTER_VARYING',
  Cidr: 'CIDR',
  Circle: 'CIRCLE',
  Date: 'DATE',
  DoublePrecision: 'DOUBLE_PRECISION',
  Inet: 'INET',
  Integer: 'INTEGER',
  Interval: 'INTERVAL',
  Json: 'JSON',
  Jsonb: 'JSONB',
  Line: 'LINE',
  Lseg: 'LSEG',
  Macaddr: 'MACADDR',
  Macaddr8: 'MACADDR8',
  Money: 'MONEY',
  Numeric: 'NUMERIC',
  Path: 'PATH',
  PgLsn: 'PG_LSN',
  PgSnapshot: 'PG_SNAPSHOT',
  Point: 'POINT',
  Polygon: 'POLYGON',
  Real: 'REAL',
  SmallInt: 'SMALLINT',
  SmallSerial: 'SMALLSERIAL',
  Serial: 'SERIAL',
  Text: 'TEXT',
  Time: 'TIME',
  TimeWithTimezone: 'TIME_WITH_TIMEZONE',
  Timestamp: 'TIMESTAMP',
  TimestampWithTimezone: 'TIMESTAMP_WITH_TIMEZONE',
  TsQuery: 'TSQUERY',
  TsVector: 'TSVECTOR',
  TxidSnapshot: 'TXID_SNAPSHOT',
  Uuid: 'UUID',
  Xml: 'XML',
} as const
export type PostgresDataType =
  (typeof PostgresDataType)[keyof typeof PostgresDataType]

export const PostgesDataTypeIdMap = {
  [16]: PostgresDataType.Boolean,
  [17]: PostgresDataType.Bytea,
  [18]: PostgresDataType.Character,
  [20]: PostgresDataType.BigInt,
  [21]: PostgresDataType.SmallInt,
  [23]: PostgresDataType.Integer,
  // [24]: REGPROC,
  [25]: PostgresDataType.Text,
  // [26]: OID,
  // [27]: TID,
  // [28]: XID,
  // [29]: CID,
  [114]: PostgresDataType.Json,
  [142]: PostgresDataType.Xml,
  // [194]: PG_NODE_TREE,
  // [210]: SMGR,
  [602]: PostgresDataType.Path,
  [604]: PostgresDataType.Polygon,
  [650]: PostgresDataType.Cidr,
  [700]: PostgresDataType.Real,
  [701]: PostgresDataType.DoublePrecision,
  // [702]: ABSTIME,
  // [703]: RELTIME,
  [704]: PostgresDataType.Interval,
  [718]: PostgresDataType.Circle,
  [774]: PostgresDataType.Macaddr8,
  [790]: PostgresDataType.Money,
  [829]: PostgresDataType.Macaddr,
  [869]: PostgresDataType.Inet,
  // [1033]: ACLITEM,
  //[1042]: BPCHAR,
  [1043]: PostgresDataType.CharacterVarying,
  [1082]: PostgresDataType.Date,
  [1083]: PostgresDataType.Time,
  [1114]: PostgresDataType.Timestamp,
  [1184]: PostgresDataType.TimeWithTimezone,
  [1186]: PostgresDataType.Interval,
  [1266]: PostgresDataType.TimeWithTimezone,
  [1560]: PostgresDataType.Bit,
  [1562]: PostgresDataType.BitVarying,
  [1700]: PostgresDataType.Numeric,
  // [1790]: REFCURSOR,
  // [2202]: REGPROCEDURE,
  // [2203]: REGOPER,
  // [2204]: REGOPERATOR,
  // [2205]: REGCLASS,
  // [2206]: REGTYPE,
  [2950]: PostgresDataType.Uuid,
  [2970]: PostgresDataType.TxidSnapshot,
  [3220]: PostgresDataType.PgLsn,
  // [3361]: PG_NDISTINCT,
  // [3402]: PG_DEPENDENCIES,
  [3614]: PostgresDataType.TsVector,
  [3615]: PostgresDataType.TsQuery,
  // [3642]: GTSVECTOR,
  // [3734]: REGCONFIG,
  // [3769]: REGDICTIONARY,
  [3802]: PostgresDataType.Jsonb,
  // [4089]: REGNAMESPACE,
  // [4096]: REGROLE,
} as const
